ZGM/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.urls import path, include

from main.views import HomeView, LandingView, PlaylistView, VideoView, AboutView, ContactView
from blog.models import Blog
from main.views import today

blogs = Blog.objects.filter(status=1).order_by('-updated')

admin.site.site_header = "ZeroGravity Admin Panel"
admin.site.index_title = "ZGM Website Administration"
admin.site.site_title = "ZeroGravity"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('artists/', include('artist.urls')),
    path('blog/', include('blog.urls')),
    path('charts/', include('chart.urls')),


    path('', HomeView, name='home'),
    path('playlists/', PlaylistView, name='playlist-view'),
    path('zgmlink/', LandingView, name='landing-view'),
    path('videos/', VideoView, name='video-view'),
    path('about/', AboutView, name='about-view'),
    path('contact/', ContactView, name='contact-view'),


    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset.html', extra_context={'blogs': blogs, 'today':today(), 'title': 'Account - Password Reset | ZeroGravity'}),
	 	name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html', extra_context={'blogs': blogs, 'today':today(), 'title': 'Account - Password Reset | ZeroGravity'}),
     	name='password_reset_done'),

	path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html', extra_context={'blogs': blogs, 'today':today(), 'title': 'Account - Password Reset Confirm | ZeroGravity'}),
		name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html', extra_context={'blogs': blogs, 'today':today(), 'title': 'Account - Password Reset Confirm | ZeroGravity'}),
     	name='password_reset_complete'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import (
    BlogListView,
    BlogDetailView,
    AuthorDetailView,
    ArchiveListView,
    TagBlogListView
)


app_name = 'blog'
urlpatterns = [
    path('', BlogListView, name='blog-list'),
    path('<slug:slug>/', BlogDetailView, name='blog-detail'),
    path('author/<slug:slug>/', AuthorDetailView, name='author-detail'),
    path('archives/<int:year>/<int:month>/', ArchiveListView, name='archive-list'),
    path('tag/<slug:slug>/', TagBlogListView, name='tagblog-list'),
]

chart/urls.py
from django.urls import path
from .views import ZGMChartView



app_name = 'chart'
urlpatterns = [
    path('zgm-top-50/', ZGMChartView, name='zgm-chart'),
    #path('cu-top-30/', CUChartView, name='cu-chart'),
    #path('unilag-top-30/', UnilagChartView, name='unilag-chart'),
    #path('landmark-top-30/', LandmarkChartView, name='landmark-chart'),

]

templates/banner.html
{% load static %}
<!-- Banner -->
<div class="container m-t-10 m-b-15">
    {% if h_ads %}
        <div style="text-align: center; font-size: 7pt; font-weight: bold; letter-spacing: 2px;">ADVERTISEMENT</div>
        <div class="flex-c-c">
            <a href="{{ h_ads.first.link }}">
                <img class="max-w-full" src="{{ h_ads.first.image.url }}" alt="IMG">
            </a>
        </div>
    {% else %}
        <div style="text-align: center; font-size: 7pt; font-weight: bold; letter-spacing: 2px;">ADVERTISEMENT</div>
        <div class="flex-c-c">
            <a href="#">
                <img class="max-w-full" src="{% static 'images/banner-01.jpg' %}" alt="IMG">
            </a>
        </div>
    {% endif %}
</div>

templates/chartnav.html
<li><a href="{% url 'chart:zgm-chart' %}">ZGM TOP 50</a></li>
<li><a href="{% url 'chart:cu-chart' %}">CU TOP 30</a></li>
<li><a href="{% url 'chart:unilag-chart' %}">UNILAG TOP 30</a></li>
<li><a href="{% url 'chart:landmark-chart' %}">LMU TOP 30</a></li>

templates/practice.html
    def save(self, *args, **kwargs):
        if self.image:
            img = Img.open(self.image)
            output = BytesIO()
            new_image = img.resize((200, 200))
            new_image.save(output, format='JPEG', quality=60)
            output.seek(0)
            self.image= InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
        super(Artist, self).save(*args, **kwargs)

templates/sidebar.html
{% load static %}
{% load crispy_forms_tags %}
	<div class="col-md-10 col-lg-4">
		<div class="p-l-10 p-rl-0-sr991 p-b-20">
			<!-- Stay Connected -->
			<div class="p-b-35">
				<div class="how2 how2-cl4 flex-s-c">
					<h3 class="f1-m-2 cl3 tab01-title">
						Stay Connected
					</h3>
				</div>

				<ul class="p-t-35">
					<li class="flex-wr-sb-c p-b-20">
						<a href="https://www.instagram.com/zerogravityy__" target="_blank" class="size-a-8 flex-c-c borad-3 size-a-8 bg-instagram fs-16 cl0 hov-cl0">
							<span class="fab fa-instagram"></span>
						</a>

						<div class="size-w-3 flex-wr-sb-c">
                            <a href="https://www.instagram.com/zerogravityy__" target="_blank">
                                <span class="f1-s-8 cl3 p-r-20">
                                    Instagram
                                </span>
                            </a>
						</div>
					</li>

					<li class="flex-wr-sb-c p-b-20">
						<a href="https://twitter.com/zerogravityy__" target="_blank" class="size-a-8 flex-c-c borad-3 size-a-8 bg-twitter fs-16 cl0 hov-cl0">
							<span class="fab fa-twitter"></span>
						</a>

						<div class="size-w-3 flex-wr-sb-c">
                            <a href="https://twitter.com/zerogravityy__" target="_blank">
                                <span class="f1-s-8 cl3 p-r-20">
                                    Twitter
                                </span>
                            </a>
						</div>
					</li>

					<li class="flex-wr-sb-c p-b-20">
						<a href="https://www.youtube.com/channel/UC4FiwnJ3R7o1Obhy0czRajQ" class="size-a-8 flex-c-c borad-3 size-a-8 bg-youtube fs-16 cl0 hov-cl0">
							<span class="fab fa-youtube"></span>
						</a>

						<div class="size-w-3 flex-wr-sb-c">
							<a href="https://www.youtube.com/channel/UC4FiwnJ3R7o1Obhy0czRajQ" target="_blank">
                                <span class="f1-s-8 cl3 p-r-20">
                                    Youtube
                                </span>
                            </a>
						</div>
					</li>
				</ul>
			</div>

			<!-- Most Popular -->
			<div class="p-b-30">
				<div class="how2 how2-cl4 flex-s-c">
					<h3 class="f1-m-2 cl3 tab01-title">
						Popular Posts
					</h3>
				</div>

				<ul class="p-t-35">
                    {% for data in popular_blogs %}
                        {% if forloop.counter < 6 %}
					<li class="flex-wr-sb-s p-b-22">
						<div class="size-a-8 flex-c-c borad-3 size-a-8 bg9 f1-m-4 cl0 m-b-6">
							{{ forloop.counter }}
						</div>
						<a href="{% url 'blog:blog-detail' data.slug %}" class="size-w-3 f1-s-7 cl3 hov-cl10 trans-03">
							{{ data.title }}
						</a>
					</li>
                        {% endif %}
                    {% endfor %}
				</ul>
			</div>

			<!-- Banner  -->
            <div class="p-t-8" style="text-align: center; font-size: 7pt; font-weight: bold; letter-spacing: 2px;">ADVERTISEMENT</div>
			<div class="flex-c-s p-b-65">
                {% if v_ads %}
                    <a href="{{ v_ads.first.link }}">
                        <img class="max-w-full" src="{{ v_ads.first.image.url }}" alt="IMG">
                    </a>
                {% else %}
                    <a href="#">
                        <img class="max-w-full" src="{% static 'images/banner-02.jpg' %}" alt="IMG">
                    </a>
                {% endif %}
			</div>

			<!-- Video -->
            {% if youtube_ads or video_ads %}
			<div class="p-b-55">
				<div class="how2 how2-cl4 flex-s-c m-b-35">
					<h3 class="f1-m-2 cl3 tab01-title">
						Featured Video
					</h3>
				</div>
                {% if youtube_ads %}
				<div>
					<div class="wrap-pic-w pos-relative">
						<img src="https://img.youtube.com/vi/{{ youtube_ads.youtube }}/mqdefault.jpg" alt="IMG">
						<button class="s-full ab-t-l flex-c-c fs-32 cl0 hov-cl10 trans-03" data-toggle="modal" data-target="#modal-video-01">
							<span class="fab fa-youtube"></span>
						</button>
					</div>
					<div class="p-tb-16 p-rl-25 bg3">
						<h5 class="p-b-5">
							<a href="https://www.youtube.com/{{ youtube_ads.youtube }}" class="f1-m-3 cl0 hov-cl10 trans-03">
								{{ youtube_ads.first.title }}
							</a>
						</h5>
						<span class="cl15">
							<a href="#" class="f1-s-4 cl8 hov-cl10 trans-03">
								by {{ youtube_ads.first.owner }}
							</a>
							<span class="f1-s-3 m-rl-3">
								-
							</span>
							<span class="f1-s-3">
								{{ youtube_ads.first.posted }}
							</span>
						</span>
					</div>
				</div>
                {% elif video_ads %}
                    <div>
                        <div class="wrap-pic-w pos-relative">
                            <video width="320" height="240" controls="controls" autoplay muted>
                                <source src="{{ video_ads.first.video.url }}" type="video/mp4">
                                <source src="{{ video_ads.first.video.url }}" type="video/mkv">
                                Your browser does not support the video tag.
                            </video>
                        </div>
                        <div class="p-tb-16 p-rl-25 bg3">
                            <h5 class="p-b-5">
                                {% if video_ads.first.link %}
                                <a href="{{ video_ads.first.link }}" class="f1-m-3 cl0 hov-cl10 trans-03">
                                    {{ video_ads.first.title }}
                                </a>
                                {% else %}
                                    <span class="f1-m-3 cl0 hov-cl10 trans-03">{{ video_ads.first.title }}</span>
                                {% endif %}
                            </h5>
                            <span class="cl15">
                                <span class="f1-s-4 cl8 hov-cl10 trans-03">
                                    by {{ video_ads.first.owner }}
                                </span>
                            </span>
                        </div>
				    </div>
                {% endif %}
			</div>
            {% endif %}

			<!-- Subscribe -->
			<div class="bg10 p-rl-35 p-t-28 p-b-65 m-b-55">
				<h5 class="f1-m-5 cl0 p-b-10">
					Subscribe
				</h5>
				<p class="f1-s-1 cl0 p-b-25">
					Subscribe to our Newsletter for new blog posts, news & photos. Let's stay updated!
				</p>
				<form method="POST" class="size-a-9">{% csrf_token %}
					{{ subscription_form|crispy }}
                    <input type="submit" name="subscribe" value="Subscribe" class="btn btn-dark btn-default">
				</form>
			</div>

            <!-- Archive -->
            <div class="p-b-37">
                <div class="how2 how2-cl4 flex-s-c">
                    <h3 class="f1-m-2 cl3 tab01-title">
                        Archive
                    </h3>
                </div>
                <ul class="p-t-32">
                    <li class="p-rl-4 p-b-19">
                        <a href="{% url 'blog:archive-list' 2020 07 %}" class="flex-wr-sb-c f1-s-10 text-uppercase cl2 hov-cl10 trans-03">
                            <span>
                                July 2020
                            </span>
                        </a>
                    </li>
                    <li class="p-rl-4 p-b-19">
                        <a href="{% url 'blog:archive-list' 2020 06 %}" class="flex-wr-sb-c f1-s-10 text-uppercase cl2 hov-cl10 trans-03">
                            <span>
                                June 2020
                            </span>
                        </a>
                    </li>

                    <li class="p-rl-4 p-b-19">
                        <a href="{% url 'blog:archive-list' 2020 05 %}" class="flex-wr-sb-c f1-s-10 text-uppercase cl2 hov-cl10 trans-03">
                            <span>
                                May 2020
                            </span>
                        </a>
                    </li>
                </ul>
            </div>

            {% if common_tags %}
			<!-- Tag -->
			<div class="p-b-55">
				<div class="how2 how2-cl4 flex-s-c m-b-30">
					<h3 class="f1-m-2 cl3 tab01-title">
						Tags
					</h3>
				</div>

				<div class="flex-wr-s-s m-rl--5">
                    {% for tag in common_tags %}
					<a href="{% url 'blog:tagblog-list' tag.slug %}" class="flex-c-c size-h-2 bo-1-rad-20 bocl12 f1-s-1 cl8 hov-btn2 trans-03 p-rl-20 p-tb-5 m-all-5">
						{{ tag }}
					</a>
                    {% endfor %}
				</div>
			</div>
            {% endif %}
		</div>
	</div>