ZGM/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.urls import path, include

from main.views import HomeView, LandingView, PlaylistView, VideoView, AboutView, ContactView
from blog.models import Blog
from main.views import today

blogs = Blog.objects.filter(status=1).order_by('-updated')

admin.site.site_header = "ZeroGravity Admin Panel"
admin.site.index_title = "ZGM Website Administration"
admin.site.site_title = "ZeroGravity"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('artists/', include('artist.urls')),
    path('blog/', include('blog.urls')),
    path('charts/', include('chart.urls')),


    path('', HomeView, name='home'),
    path('playlists/', PlaylistView, name='playlist-view'),
    path('zgmlink/', LandingView, name='landing-view'),
    path('videos/', VideoView, name='video-view'),
    path('about/', AboutView, name='about-view'),
    path('contact/', ContactView, name='contact-view'),


    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset.html', extra_context={'blogs': blogs, 'today':today(), 'title': 'Account - Password Reset | ZeroGravity'}),
	 	name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html', extra_context={'blogs': blogs, 'today':today(), 'title': 'Account - Password Reset | ZeroGravity'}),
     	name='password_reset_done'),

	path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html', extra_context={'blogs': blogs, 'today':today(), 'title': 'Account - Password Reset Confirm | ZeroGravity'}),
		name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html', extra_context={'blogs': blogs, 'today':today(), 'title': 'Account - Password Reset Confirm | ZeroGravity'}),
     	name='password_reset_complete'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import RegisterView, UserProfileView, ArtistApplicationView, SongSubmissionView
from .forms import AuthForm
from blog.models import Blog
from main.views import today

blogs = Blog.objects.filter(status=1).order_by('-updated')



app_name = 'account'
urlpatterns = [
    path('register/', RegisterView, name='register'),
    path('profile/', UserProfileView, name='profile'),
    path('artist-application/', ArtistApplicationView, name='artistapplication-view'),
    path('song-submission/', SongSubmissionView, name='songsubmission-view'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

 	path('login/', auth_views.LoginView.as_view(template_name='account/login.html',
                                                redirect_authenticated_user=True,
                                                authentication_form=AuthForm,
                                                extra_context={'blogs': blogs, 'today':today(), 'title': 'Account - Log In | ZeroGravity'}), name='login',),
]

artist/urls.py
from django.urls import path
from .views import (
    ArtistView,
    Polls,
)


app_name = 'artist'
urlpatterns = [
    path('', ArtistView, name='artist-view'),
    path('polls/', Polls, name='polls'),
]

blog/urls.py
from django.urls import path
from .views import (
    BlogListView,
    BlogDetailView,
    AuthorDetailView,
    ArchiveListView,
    TagBlogListView
)


app_name = 'blog'
urlpatterns = [
    path('', BlogListView, name='blog-list'),
    path('<slug:slug>/', BlogDetailView, name='blog-detail'),
    path('author/<slug:slug>/', AuthorDetailView, name='author-detail'),
    path('archives/<int:year>/<int:month>/', ArchiveListView, name='archive-list'),
    path('tag/<slug:slug>/', TagBlogListView, name='tagblog-list'),
]

chart/urls.py
from django.urls import path
from .views import ZGMChartView



app_name = 'chart'
urlpatterns = [
    path('zgm-top-50/', ZGMChartView, name='zgm-chart'),
    #path('cu-top-30/', CUChartView, name='cu-chart'),
    #path('unilag-top-30/', UnilagChartView, name='unilag-chart'),
    #path('landmark-top-30/', LandmarkChartView, name='landmark-chart'),

]

main/models.py
from django.db import models
from django.utils import timezone
from taggit.managers import TaggableManager


class University(models.Model):
    name = models.CharField(max_length=150)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        verbose_name_plural = "Universities"

    def __str__(self):
        return self.name





OPTIONS = (
    (1,"Horizontal - 728x90"),
    (2,"Vertical - 300x600"),
    (3,"Video - 720x405"),
    (4,"Youtube video - 720x405")
)

class Advertisement(models.Model):
    title       = models.CharField(max_length=150)
    owner       = models.CharField(max_length=150)
    type        = models.IntegerField(choices=OPTIONS, default=1)
    image       = models.ImageField(upload_to='advertisement', blank=True, null=True, help_text='Optional')
    video       = models.FileField(upload_to='advertisement', blank=True, null=True, help_text='Optional')
    youtube     = models.CharField(max_length=150, blank=True, null=True, help_text='Optional')
    description = models.TextField(blank=True, null=True, help_text='Required only for videos and youtube ads')
    link        = models.URLField(max_length=200, help_text='Required only for youtube video ads', blank=True, null=True)
    active      = models.BooleanField(default=True)
    posted      = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-posted']

    def __str__(self):
        return self.title





class Video(models.Model):
    title       = models.CharField(max_length=200)
    feature     = models.TextField(max_length=225, null=True, blank=True)
    artist      = TaggableManager()
    description = models.TextField(max_length=225, null=True, blank=True, help_text='Optional')
    university  = models.ManyToManyField('University', blank=True, related_name='institutions')
    link        = models.CharField(max_length=225, verbose_name='Youtube Link')
    active      = models.BooleanField(default=True)
    created     = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.title} by {self.feature}'




class Audio(models.Model):
    title       = models.CharField(max_length=200)
    file        = models.FileField(upload_to='audio')
    type        = models.CharField(max_length=200)
    active      = models.BooleanField(default=True)
    date        = models.DateTimeField(default=timezone.now)





class CustomerService(models.Model):
    name    = models.CharField(max_length=200)
    email   = models.EmailField(max_length=200)
    phone   = models.IntegerField(blank=True, null=True, verbose_name='Phone Number')
    content = models.TextField(verbose_name='Message')
    date    = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-date']
        verbose_name_plural = 'Customer Service'

    def __str__(self):
        return self.name

main/forms.py
from django import forms
from .models import CustomerService

class CustomerServiceForm(forms.ModelForm):
    class Meta:
        model = CustomerService
        fields = [
            'name',
            'email',
            'phone',
            'content',
        ]


    def __init__(self, *args, **kwargs):
        super(CustomerServiceForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'})
        self.fields['name'].label = False
        self.fields['email'].widget = forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'})
        self.fields['email'].label = False
        self.fields['phone'].widget = forms.NumberInput(attrs={'class': 'form-control', 'placeholder':'Phone Number(Optional)'})
        self.fields['phone'].label = False
        self.fields['content'].widget = forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'How can we help you?'})
        self.fields['content'].label = False
        self.fields['content'].widget.attrs['rows'] = 10

main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from datetime import datetime, date
from django.core.mail import send_mass_mail

from .models import Video, Advertisement
from artist.models import Artist
from blog.models import Blog
from chart.models import Track
from account.models import Subscriber
from .forms import CustomerServiceForm
from account.forms import SubscriptionForm



def sat():
    today_date = date.today()
    if today_date.strftime('%A') == 'Saturday':
        return today_date
    else:
        today = date.today().toordinal()
        lastWeek = today-7
        sunday = lastWeek - (lastWeek % 7)
        saturday = sunday + 6
        return date.fromordinal(saturday)



def today():
    today_date = datetime.now()
    return today_date




def LandingView(request):
    blogs = Blog.objects.filter(status=1).order_by('-updated')
    context = {
        'today': today(),
        'blogs': blogs,
        'title': 'ZeroGravity - Music Charts, Blog, Playlist & Artists | ZeroGravity',
    }
    return render(request, "main/zgmlink.html", context)





def HomeView(request):
    if request.method == 'POST' and 'subscribe' in request.POST:
        subscription_form = SubscriptionForm(request.POST or None)
        if subscription_form.is_valid():
            subscriber_email = request.POST.get('subscriber_email')
            subscriber = Subscriber.objects.create(email=subscriber_email)
            subscriber.save()

            message1 = ('ZeroGravity Music Team',
            'Thank you for subscribing to ZeroGravity.\nWe would keep you updated on the best musical content from ZeroGravity Music.',
            'zgm@zerogravity.com.ng',
            [subscriber_email])

            message2 = ('Newsletter Subscription Notification', f'This is to notify you that {subscriber_email} just subscribed to your newsletter',
                     'zgm@zerogravity.com.ng', ['zerogravityymusic@gmail.com'])

            send_mass_mail((message1, message2), fail_silently=True)

            messages.success(request, f'You have subscribed to ZeroGravity Music!')
            return redirect('home')
    else:
        subscription_form = SubscriptionForm()

    blogs = Blog.objects.filter(status=1)
    blog = blogs.order_by('-updated')
    popular = blogs.order_by('?')
    artists = Artist.objects.filter(status=1).order_by('?')[:6]
    tracks = Track.objects.filter(submission=1)
    recent = tracks.order_by('-released')[:10]
    artist_track = tracks.order_by('-released')
    zgmtop10 = tracks.filter(status=1).filter(zgm_rank__gte=1, zgm_rank__lte=10).order_by('zgm_rank')
    videos = Video.objects.filter(active=True)
    homevideos = videos.order_by('-created')[:5]
    ads = Advertisement.objects.filter(active=True)
    h_ads = ads.filter(type=1).order_by('?')
    v_ads = ads.filter(type=2).order_by('?')
    video_ads = ads.filter(type=3).order_by('?')
    youtube_ads = ads.filter(type=4).order_by('?')
    common_tags = Blog.tags.most_common()[:5]

    context = {
        'today': today(),
        'charted': sat(),
    	'artists': artists,
        'tracks': artist_track,
        'blogs': blog,
        'popular_blogs': popular,
        'recent': recent,
        'zgmtop10': zgmtop10,
        'common_tags': common_tags,
        'videos': homevideos,
        'h_ads': h_ads,
        'v_ads': v_ads,
        'video_ads': video_ads,
        'youtube_ads': youtube_ads,
        'subscription_form': subscription_form,
        'title': 'ZeroGravity - Music Charts, Blog, Playlist & Artists | ZeroGravity',
    }
    return render(request, "main/home.html", context)





def PlaylistView(request):
    blogs = Blog.objects.filter(status=1).order_by('-updated')
    context = {
        'today': today(),
        'blogs': blogs,
        'title': 'Playlists | ZeroGravity',
    }
    return render(request, "main/playlist.html", context)





def VideoView(request):
    videos = Video.objects.filter(active=True)
    videopage = videos.order_by('-created')
    blogs = Blog.objects.filter(status=1).order_by('-updated')
    context = {
        'today': today(),
        'blogs': blogs,
        'videos': videopage,
        'title': 'Music Videos | ZeroGravity',
    }
    return render(request, "main/video.html", context)





def AboutView(request):
    blogs = Blog.objects.filter(status=1).order_by('-updated')
    context = {
        'today': today(),
        'blogs': blogs,
        'title': 'About Us | ZeroGravity',
    }
    return render(request, "main/about.html", context)





def ContactView(request):
    blogs = Blog.objects.filter(status=1).order_by('-updated')
    if request.method == 'POST':
        service_form = CustomerServiceForm(request.POST or None)
        if service_form.is_valid():
            customer_email = request.POST.get('email')
            request_content = request.POST.get('content')
            service_form.save()

            message1 = ('ZeroGravity Customer Support',
            'Thank you for contacting ZeroGravity Music.\nWe would get back to you shortly regarding your request.',
            'zgm@zerogravity.com.ng',
            [customer_email])

            message2 = ('Customer Service Request', f'You just got a request from {customer_email}.\n\nContent: {request_content}.\n\n Please attend to the customer as soon as possible.',
                     'zgm@zerogravity.com.ng', ['zerogravityymusic@gmail.com'])

            send_mass_mail((message1, message2), fail_silently=True)

            messages.success(request, f'Your message was sent successfully')
            return redirect('contact-view')
    else:
        service_form = CustomerServiceForm()

    context = {
        'today': today(),
        'blogs': blogs,
        'form': service_form,
        'title': 'Contact Us | ZeroGravity',
    }
    return render(request, "main/contact.html", context)

main/templates/main/home_bg.html
{% load static %}
<!-- Headline -->
<div class="container">
	<div class="bg0 flex-wr-sb-c p-rl-20 p-tb-8">
		<div class="f2-s-1 p-r-30 size-w-0 m-tb-6 flex-wr-s-c">
			<span class="text-uppercase cl2 p-r-8">
				Latest Blogs:
			</span>
            {% if blogs %}
			<span class="dis-inline-block cl6 slide100-txt pos-relative size-w-0" data-in="fadeInDown" data-out="fadeOutDown">
                {% for data in blogs %}
                    {% if forloop.counter <= 4 %}
                <span class="dis-inline-block slide100-txt-item animated visible-false">
					{{ data.title }}
				</span>
                    {% endif %}
				{% endfor %}
			</span>
            {% endif %}
		</div>
	</div>
</div>

<!-- Feature post -->
<section class="bg0">
    {% if request.user_agent.is_pc or request.user_agent.is_tablet %}
	<div class="container">
		<div class="row m-rl--1">
			<div class="col-md-6 p-rl-1 p-b-2">
				<div class="bg-img1 size-a-3 how1 pos-relative" style="background-image: url(../../../static/images/homebg.jpg);">
					<a href="{% url 'chart:zgm-chart' %}" class="dis-block how1-child1 trans-03"></a>

					<div class="flex-col-e-s s-full p-rl-25 p-tb-20">
						<a href="#" class="dis-block how1-child2 f1-s-2 cl0 bo-all-1 bocl0 hov-btn1 trans-03 p-rl-5 p-t-2">
							ZGM TOP 50 - Song Of The Week
						</a>
                        {% if zgmtop10 %}
                            {% if zgmtop10.first.link %}
                                <h3 class="how1-child2 m-t-14 m-b-10">
                                    <a href="{{ zgmtop10.first.link }}" target="_blank" class="how-txt1 size-a-6 f1-m-5 cl0 hov-cl10 trans-03" style="color: lightgrey;">
                                        {{ zgmtop10.first.title|capfirst }} <span class="f1-m-2">by {{ zgmtop10.first.artist|capfirst }}</span>
                                    </a>
                                </h3>
                            {% else %}
                                <h3 class="how1-child2 m-t-14 m-b-10">
                                    <span class="how-txt1 size-a-6 f1-m-5 cl0 hov-cl10 trans-03" style="color: lightgrey;">
                                        {{ zgmtop10.first.title|capfirst }} <span class="f1-m-2">by {{ zgmtop10.first.artist|capfirst }}</span>
                                    </span>
                                </h3>
                            {% endif %}
                        {% endif %}
					</div>
				</div>
			</div>

            {% if blogs %}
			<div class="col-md-6 p-rl-1">
				<div class="row m-rl--1">
					<div class="col-12 p-rl-1 p-b-2">
						<div class="bg-img1 size-a-4 how1 pos-relative" style="background-image: url({{ blogs.first.image.url }});">
							<a href="{% url 'blog:blog-detail' blogs.first.slug %}" class="dis-block how1-child1 trans-03"></a>

							<div class="flex-col-e-s s-full p-rl-25 p-tb-24">
								<a href="{% url 'blog:blog-list' %}" class="dis-block how1-child2 f1-s-2 cl0 bo-all-1 bocl0 hov-btn1 trans-03 p-rl-5 p-t-2">
									Latest Blog
								</a>

								<h3 class="how1-child2 m-t-14">
									<a href="{% url 'blog:blog-detail' blogs.first.slug %}" class="how-txt1 size-a-7 f1-l-2 cl0 hov-cl10 trans-03" style="color: lightgrey;">
										{{ blogs.first.title }}
									</a>
								</h3>
							</div>
						</div>
					</div>
                    {% for data in blogs %}
                        {% if forloop.counter > 1 and forloop.counter <= 3 %}
					<div class="col-sm-6 p-rl-1 p-b-2">
						<div class="bg-img1 size-a-5 how1 pos-relative" style="background-image: url({{ data.image.url }});">
							<a href="{% url 'blog:blog-detail' data.slug %}" class="dis-block how1-child1 trans-03"></a>

							<div class="flex-col-e-s s-full p-rl-25 p-tb-20">
								<a href="{% url 'blog:blog-list' %}" class="dis-block how1-child2 f1-s-2 cl0 bo-all-1 bocl0 hov-btn1 trans-03 p-rl-5 p-t-2">
									Blog
								</a>

								<h3 class="how1-child2 m-t-14">
									<a href="{% url 'blog:blog-detail' data.slug %}" class="how-txt1 size-h-1 f1-m-1 cl0 hov-cl10 trans-03">
										{{ data.title }}
									</a>
								</h3>
							</div>
						</div>
					</div>
                        {% endif %}
                    {% endfor %}
				</div>
			</div>
            {% endif %}
		</div>
	</div>

	{% elif request.user_agent.is_mobile %}
    <div class="container">
		<div class="row m-rl--1">
			<div class="col-md-6 p-rl-1 p-b-2">
				<div class="bg-img1 size-a-4 how1 pos-relative" style="background-image: url({{ zgmtop10.first.artwork.url }});">
					<a href="{% url 'chart:zgm-chart' %}" class="dis-block how1-child1 trans-03"></a>

					<div class="flex-col-e-s s-full p-rl-25 p-tb-20">
						<a href="#" class="dis-block how1-child2 f1-s-2 cl0 bo-all-1 bocl0 hov-btn1 trans-03 p-rl-5 p-t-2">
							ZGM TOP 50 - Song Of The Week
						</a>
                        {% if zgmtop10 %}
                            {% if zgmtop10.first.link %}
                                <h3 class="how1-child2 m-t-14 m-b-10">
                                    <a href="{{ zgmtop10.first.link }}" target="_blank" class="how-txt1 size-a-6 f1-m-5 cl0 hov-cl10 trans-03" style="color: lightgrey;">
                                        {{ zgmtop10.first.title|capfirst }} <span class="f1-m-2">by {{ zgmtop10.first.artist|capfirst }}</span>
                                    </a>
                                </h3>
                            {% else %}
                                <h3 class="how1-child2 m-t-14 m-b-10">
                                    <span class="how-txt1 size-a-6 f1-m-5 cl0 hov-cl10 trans-03" style="color: lightgrey;">
                                        {{ zgmtop10.first.title|capfirst }} <span class="f1-m-2">by {{ zgmtop10.first.artist|capfirst }}</span>
                                    </span>
                                </h3>
                            {% endif %}
                        {% endif %}
					</div>
				</div>
			</div>

            {% if blogs %}
			<div class="col-md-6 p-rl-1">
				<div class="row m-rl--1">
					<div class="col-12 p-rl-1 p-b-2">
						<div class="bg-img1 size-a-4 how1 pos-relative" style="background-image: url({{ blogs.first.image.url }});">
							<a href="{% url 'blog:blog-detail' blogs.first.slug %}" class="dis-block how1-child1 trans-03"></a>

							<div class="flex-col-e-s s-full p-rl-25 p-tb-24">
								<a href="{% url 'blog:blog-list' %}" class="dis-block how1-child2 f1-s-2 cl0 bo-all-1 bocl0 hov-btn1 trans-03 p-rl-5 p-t-2">
									Latest Blog
								</a>

								<h3 class="how1-child2 m-t-14">
									<a href="{% url 'blog:blog-detail' blogs.first.slug %}" class="how-txt1 size-a-7 f1-l-2 cl0 hov-cl10 trans-03" style="color: lightgrey;">
										{{ blogs.first.title }}
									</a>
								</h3>
							</div>
						</div>
					</div>
				</div>
			</div>
            {% endif %}
		</div>
	</div>

	{% endif %}
</section>

main/templates/main/home_recent.html
{% if recent %}
<div class="container p-t-60">
    <div class="how2 how2-cl1 flex-s-c">
        <h3 class="f1-m-2 cl12 tab01-title">
            Recent Tracks
        </h3>
    </div>
   <section class="customer-logos slider pt-3">
       {% for data in recent %}
           {% if data.link %}
                <div class="slide"><a target="_blank" href="{{ data.link }}"><img src="{{ data.artwork.url }}"></a>
                    <div class="f1-s-4" style="text-align: center;"><a target="_blank" style="color: grey" href="{{ data.link }}">{{ data.title|capfirst }} - {{ data.artist|capfirst }}</a></div>
                </div>
           {% else %}
                <div class="slide"><img src="{{ data.artwork.url }}">
                    <div class="f1-s-4" style="text-align: center;">{{ data.title }} - {{ data.artist }}</div>
                </div>
           {% endif %}
       {% endfor %}
   </section>
</div>
{% endif %}

main/templates/main/playlist.html
{% extends "base.html" %}

{% block nav %}
    <ul class="main-menu justify-content-center">
        <li><a href="{% url 'home' %}">HOME</a></li>

        <li><a href="{% url 'chart:zgm-chart' %}">CHARTS</a></li>

        <li><a href="{% url 'blog:blog-list' %}">BLOG</a></li>

        <li class="main-menu-active">
            <a href="{% url 'playlist-view' %}">PLAYLISTS</a>
        </li>

        <li><a href="{% url 'artist:artist-view' %}">ARTISTS</a></li>

        <li><a href="{% url 'video-view' %}">VIDEOS</a></li>

        <li class="main-menu-dropdown">
            <a href="#">ACCOUNT</a>
            <ul class="sub-menu">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'account:profile' %}">Profile</a></li>
                    <li><a href="{% url 'account:songsubmission-view' %}">Song Submission</a></li>
                    <li><a href="{% url 'account:logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'account:register' %}">Sign Up</a></li>
                    <li><a href="{% url 'account:login' %}">Log In</a></li>
                    <li><a href="{% url 'account:songsubmission-view' %}">Song Submission</a></li>
                {% endif %}
            </ul>
        </li>
    </ul>
{% endblock nav %}

{% block content %}
	<!-- Breadcrumb -->
	<div class="container">
		<div class="bg0 flex-wr-sb-c p-rl-20 p-tb-8">
			<div class="f2-s-1 p-r-30 m-tb-6">
				<a href="{% url 'home' %}" class="breadcrumb-item f1-s-3 cl9">
					Home
				</a>
				<span class="breadcrumb-item f1-s-3 cl9">
					Playlists
				</span>
			</div>
		</div>
	</div>

    <!-- Page heading -->
	<div class="container p-t-4 p-b-100">
		<h2 class="f1-l-1 cl2" style="text-align: center">
			Playlists
		</h2>
	</div>

    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6">
                <iframe src="https://embed.music.apple.com/ng/playlist/cus-top-30/pl.u-e98lkNqtadaqLrg" style="border:5px solid lightgrey; border-radius: 16px" width="100%" height="400" allowfullscreen allow="encrypted-media"></iframe>
            </div>
            <div class="col-lg-6 col-md-6">
                <iframe src="https://audiomack.com/embed/playlist/zerogravityy__/cus-top-30" style="border:5px solid lightgrey; border-radius: 16px" width="100%" height="400" allowfullscreen scrolling="no" allow="encrypted-media"></iframe>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="mt-4 mb-4">
            <a href="https://music.apple.com/ng/playlist/cus-top-30/pl.u-e98lkNqtadaqLrg" class="btn btn-outline-secondary btn-block" role="button" target="_blank"><span style="font-weight: bold; color: darkred">Apple Music ZGM Next Gen: Top 50</span></a>
            <br>
            <a href="https://audiomack.com/playlist/zerogravityy__/cus-top-30" class="btn btn-outline-secondary btn-block" role="button" target="_blank"><span style="font-weight: bold; color: darkred">Audiomack ZGM Next Gen: Top 50</span></a>
            <br>
        </div>
    </div>
{% endblock content %}

main/templates/main/video.html
{% extends "base.html" %}

{% block nav %}
    <ul class="main-menu justify-content-center">
        <li><a href="{% url 'home' %}">HOME</a></li>

        <li><a href="{% url 'chart:zgm-chart' %}">CHARTS</a></li>

        <li><a href="{% url 'blog:blog-list' %}">BLOG</a></li>

        <li><a href="{% url 'playlist-view' %}">PLAYLISTS</a></li>

        <li><a href="{% url 'artist:artist-view' %}">ARTISTS</a></li>

        <li class="main-menu-active">
            <a href="{% url 'video-view' %}">VIDEOS</a>
        </li>

        <li class="main-menu-dropdown">
            <a href="#">ACCOUNT</a>
            <ul class="sub-menu">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'account:profile' %}">Profile</a></li>
                    <li><a href="{% url 'account:songsubmission-view' %}">Song Submission</a></li>
                    <li><a href="{% url 'account:logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'account:register' %}">Sign Up</a></li>
                    <li><a href="{% url 'account:login' %}">Log In</a></li>
                    <li><a href="{% url 'account:songsubmission-view' %}">Song Submission</a></li>
                {% endif %}
            </ul>
        </li>
    </ul>
{% endblock nav %}

{% block content %}
	<!-- Breadcrumb -->
	<div class="container">
		<div class="bg0 flex-wr-sb-c p-rl-20 p-tb-8">
			<div class="f2-s-1 p-r-30 m-tb-6">
				<a href="{% url 'home' %}" class="breadcrumb-item f1-s-3 cl9">
					Home
				</a>
				<span class="breadcrumb-item f1-s-3 cl9">
					Videos
				</span>
			</div>
		</div>
	</div>

    <!-- Page heading -->
	<div class="container p-t-4 p-b-100">
		<h2 class="f1-l-1 cl2" style="text-align: center">
			Videos
		</h2>
	</div>

    <div class="container">
        <div class="row p-b-100">
            {% for data in videos %}
            <div class="videomedia  col-lg-6 col-md-6">
                <div class="embed-responsive embed-responsive-16by9">
                  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{ data.link }}" allowfullscreen></iframe>
                </div>
                <span class="f1-m-1" style="font-weight: bold; color: darkred;">{{ data.title }}</span>
                <h5 class="f1-s-7" style="color: grey;">{{ data.feature|capfirst }}</h5>
                <p class="f2-s-1">{{ data.description|capfirst }}</p><br><br>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}